version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: contentforge-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - contentforge_mongo_data:/data/db
    networks:
      - contentforge-network

  # Uncomment below if you want to run backend/frontend in Docker too
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: contentforge-backend
  #   restart: unless-stopped
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - MONGO_URL=mongodb://mongodb:27017
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - contentforge-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: contentforge-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://localhost:8001
  #   depends_on:
  #     - backend
  #   networks:
  #     - contentforge-network

volumes:
  contentforge_mongo_data:

networks:
  contentforge-network:
    driver: bridge